### ISSUE TITLE
Menyen er usynleg

### ISSUE THREAD

**Issue by dittaeva** [beatricebieuville/plantemangfald-site#1]
Kvit fontfarge med tynn font, på lyseblå bakgrunn fungerer ikkje. Menyen er faktisk usynleg. Det fungerer med logoen på grunn av plasseringa og fordi den er mykje tjukkare.

Enten må bakgrunnen endrast eller fontfargen.

**Comment by dittaeva** [comment]
Eg trur ei løysing kan vere å gjera at menybakgrunnen blir vist med ein gong ein beveger seg nedover på sida.

**Comment by beatricebieuville** [comment]
Fixed
