### ISSUE TITLE
Roald Dahl quotation

### ISSUE THREAD

**Issue by dittaeva** [beatricebieuville/plantemangfald-site#3]
The Roald Dahl quotation is cue, but I fear it will not be understood with words like meadows, delectable, buttercup. Eg har funne avsnittet i norsk Charlie og sjokoladefabrikken, men [der](https://www.nb.no/items/a20fb43c003b279dcd4b54e18e1d59f7?page=59&searchText=pr%C3%B8v) er det ganske annleis.

Finst det eit anna sitat frå boka, eller ein annan stad i den norske omsettinga som kan brukast?

**Comment by beatricebieuville** [comment]
I think the norwegian works just fine. I used it instead of the english.
