### ISSUE TITLE
Rettar til Github-repositoriet

### ISSUE THREAD

**Issue by dittaeva** [beatricebieuville/plantemangfald-site#4]
Eg skulle gjerne lagt til «milestones», men det ser det ikkje ut til at eg kan gjera. Eg reknar med at det er fordi eg ikkje har nok rettar til redigering av repositoriet.

**Comment by beatricebieuville** [comment]
eg ser ikkje at eg redigera rettane din til repositoriet. Men eg kan laga Milestones sjølv...
